baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MyDecisive Documentation'

# theme stuff here

theme = "hugo-book" # https://github.com/alex-shpak/hugo-book

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'

# theme = 'ananke' this is a basic/default but not really for docs
# theme = 'docsy' <-- this looks great on paper but very complicated error-prone setup

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = truea  # enable embedded image render hook

